### ISSUE TITLE
COPR issues

### ISSUE THREAD

**Issue by nmilosev** [fedora-python/pyp2rpm#76] opened 2016-08-17 20:35 UTC
Hello there!

When trying to build Keras from PyPI on COPR for F24 the build fails. Here is the log:

https://copr-be.cloud.fedoraproject.org/results/nmilosev/Keras/fedora-24-x86_64/00442293-python-Keras/build.log.gz

As you can see the build for Python 2.7 works fine, however when building for Python 3, there are several issues:

```
....
writing manifest file 'Keras.egg-info/SOURCES.txt'
Copying Keras.egg-info to /builddir/build/BUILDROOT/python-Keras-1.0.7-1.fc24.x86_64/usr/lib/python3.5/site-packages/Keras-1.0.7-py3.5.egg-info
running install_scripts
+ /usr/lib/rpm/find-debuginfo.sh --strict-build-id -m --run-dwz --dwz-low-mem-die-limit 10000000 --dwz-max-die-limit 110000000 /builddir/build/BUILD/Keras-1.0.7
/usr/lib/rpm/sepdebugcrcfix: Updated 0 CRC32s, 0 CRC32s did match.

...

Processing files: python3-Keras-1.0.7-1.fc24.noarch
error: File not found: /builddir/build/BUILDROOT/python-Keras-1.0.7-1.fc24.x86_64/usr/lib/python3.5/site-packages/Keras_1.0.7_py3.4.egg_info
RPM build errors:
    File not found: /builddir/build/BUILDROOT/python-Keras-1.0.7-1.fc24.x86_64/usr/lib/python3.5/site-packages/Keras_1.0.7_py3.4.egg_info
Child return code was: 1
EXCEPTION: [Error()]
...
```

It tries to find `/builddir/build/BUILDROOT/python-Keras-1.0.7-1.fc24.x86_64/usr/lib/python3.5/site-packages/Keras_1.0.7_py3.4.egg_info` however it should be looking for: `/builddir/build/BUILDROOT/python-Keras-1.0.7-1.fc24.x86_64/usr/lib/python3.5/site-packages/Keras-1.0.7-py3.5.egg-info`

Several problems here:
1. 3.5 vs 3.4
2. after version (`1.0.7`) there is one time an underscore and the other one is dash (which even makes F23 builds fail)

I'm not sure if this is Keras related, COPR related, or pyp2rpm related.

Halp! :)

**Comment by nmilosev** [comment] 2016-08-17 20:43
Tested locally (f24, py3.5.1) - everything is working fine. Any advice?

**Comment by nmilosev** [comment] 2016-08-17 20:48
Another weird thing: https://copr.fedorainfracloud.org/coprs/nmilosev/Keras/build/442300/

You can see it's a f24 chroot, but it is bulding a fc23 package? So it is COPR related?

**Comment by nmilosev** [comment] 2016-08-17 20:53
Uploading the SRPM works just fine: https://copr.fedorainfracloud.org/coprs/nmilosev/Keras/build/442301/ not sure what to do next

**Comment by hroncok** [comment] 2016-08-17 21:29
cc @xsuchy

**Comment by xsuchy** [comment] 2016-08-18 09:16
> Another weird thing: https://copr.fedorainfracloud.org/coprs/nmilosev/Keras/build/442300/
> You can see it's a f24 chroot, but it is bulding a fc23 package? So it is COPR related?

The SRPM has .fc23 because the SRPM is build on F23 machine. But the binary RPM is build normaly in f24 chroot. So that is not problem.

**Comment by xsuchy** [comment] 2016-08-18 09:19
> Tested locally (f24, py3.5.1) - everything is working fine. Any advice?

The machine which runs pyp2rpm is F23 so it using pyp2rpm-3.1.2-1.fc23.noarch. Not sure if this is the cause thou.

**Comment by mcyprian** [comment] 2017-07-04 19:48
Package Keras can be now built successfully for both Python 2 and Python 3, closing this.

**Closed as completed by mcyprian** 2017-07-04 19:48 UTC
Labels: COPR

**Comment by nmilosev** [comment] 2017-07-05 11:39
Thanks Michal! :)
