### ISSUE TITLE
Use the lastest stable version of the package by default

### ISSUE THREAD

**Issue by mcyprian** [fedora-python/pyp2rpm#141] opened 2017-10-11 14:27 UTC
When I run `pyp2rpm Django` without -v switch. Spec file for alpha version 2.0a1 is generated. I guess alpha/beta versions should be ignored. Django version 1.11.6 should be used in this case. Do you agree @irushchyshyn @hroncok?

**Comment by hroncok** [comment] 2017-10-12 09:57
Agreed (if stable version exists). Also, `--pre` might be implemented.

**Comment by gordonmessmer** [comment] 2019-08-05 05:19
It looks like pip decides whether a release is a pre-release by checking for ['a', 'b', 'c', 'rc', 'dev'] in a version number:

https://github.com/pypa/pip/blob/master/src/pip/_vendor/distlib/version.py

I'll work out how many parts of that need to be copied out for this feature.  It might be just NormalizedVersion.is_prerelease...

**Comment by gordonmessmer** [comment] 2020-04-09 05:42
This should be resolved in v.3.3.4. Please re-open if you can reproduce the issue.

**Closed as completed by gordonmessmer** 2020-04-09 05:42 UTC
Labels: enhancement
