### ISSUE TITLE
argparse not install as a dependency via pip

### ISSUE THREAD

**Issue by chriscowley** [fedora-python/pyp2rpm#12] opened 2015-07-16 09:20 UTC
On clean Centos install, run:

```
pip install pyp2rpm
pyp2rpm -n <module-name>
```

returns:

```
Traceback (most recent call last):
  File "/usr/bin/pyp2rpm", line 9, in <module>
    load_entry_point('pyp2rpm==1.1.2', 'console_scripts', 'pyp2rpm')()
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 299, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2229, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1948, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.6/site-packages/pyp2rpm/bin.py", line 1, in <module>
    import argparse
ImportError: No module named argparse
```

Resolution: `pip install argparse`

That second step should not really be necessary

**Comment by rkuska** [comment] 2015-07-16 09:28
Hi Chris,

we've switched to `click` which is correctly listed in `setup.py` requirments, the problem is that we currently don't have official release, pyp2rpm is  under ongoing change of ownership but we will resolve this as soon as possible and release a new version.

**Comment by rkuska** [comment] 2015-07-16 09:33
ETA seems to be first week of august because of EuroPython and some other more important tasks, I hope you don't mind.

**Comment by chriscowley** [comment] 2015-07-16 11:34
that ETA is no problem at all

**Comment by chriscowley** [comment] 2015-07-16 11:37
Click looks cool, I had never heard of it. Noted and will use next time I need to create a CLI tool :-)

**Comment by rkuska** [comment] 2015-08-04 07:48
This will be resolved in a new release of py2rpm, master branch is already fixed so I am closing this  :-)

**Closed as completed** 2015-08-04 07:47 UTC

**Comment by rkuska** [comment] 2015-08-17 14:36
Just FYI, 2.0.0 was just released.
