### ISSUE TITLE
Locale built for epel7 will use undefined macro python3dist

### ISSUE THREAD

**Issue by tuxmaster** [fedora-python/pyp2rpm#174] opened 2018-08-13 05:58 UTC
Using version 3.3.2 to create spec files for epel7 on centos7 will create spec files with entry's like:

> BuildRequires:  python3dist(setuptools)

But when I try to built the result via mock it fails with:

> Error: No Package found for python3dist(setuptool)

The call to pyp2rpm was:

> ~/.local/bin/pyp2rpm -o epel7 dist/sample-0.1.0.tar.gz  -b 3 -d /home/user/RPM/ > >/home/user/RPM/SPECS/sample.spec

**Comment by hroncok** [comment] 2018-08-13 10:04
Hi. Thanks for the report. Our resources to maintain pyp2rpm are now very limited. I don't think we will be able to fix this any time soon.

**Comment by nkadel** [comment] 2019-05-02 18:56
The fix is pretty easy. Instead of using the "python3dist" macro, use "python%{python3_pkgversion}-", as is used for EPEL and EPEL compatible RPM's on Fedora. See https://bugzilla.redhat.com/show_bug.cgi?id=1442709 for details.

It will help generate compatible .spec files on RHEL and Fedora, consistently, to use this.

**Comment by gordonmessmer** [comment] 2019-08-04 21:40
This issue was caused by specifying the "epel7" distro, but using the default "fedora" template.  It was fixed by commit 7f2d9a00e50b59b0087edc2c79763e57b0129a4e which will be included in a future release.

The current release should produce proper results if "-t epel7" is specified instead of "-o epel7".

**Comment by nkadel** [comment] 2019-08-04 22:39
The whole setup is about to be disrupted by RHEL 7.7 publishing "python3" packages.

**Comment by hroncok** [comment] 2019-08-04 22:44
> The whole setup is about to be disrupted by RHEL 7.7 publishing "python3" packages.

How exactly?

**Comment by nkadel** [comment] 2019-08-04 23:57
All of the "epel-7" built packages that rely on python36 python modules, or that build with "%pytthon3_package" set to "python36" right now, will need to be reset and rebuilt with "python3" to use the build-in "python3". That is unless RHEL decides to repeat the fiasco that happened with ansible overlap with already existing and relied upon EPEL packages.

Bring popcorn, this is going to be fun.

**Comment by hroncok** [comment] 2019-08-05 08:13
The python3 RHEL 7.7 package provides and obsoletes python36. python36 is going to be retired from EPEL. No rebuilds are needed. Except for some buggy corner cases, the transition is planned to go smooth. Keep your popcorn for other things.

**Comment by nkadel** [comment] 2019-08-09 13:00
Ohhh, I definitely need popcorn. Obsoleting python36 in the “Obsoletes:” sense would break every live python36 environment, including the tools I’ve packaged for airflow, Samba, and hundreds of RPMs.

I’m glad to see the update, but there are going to be a *lot* of corner cases.

**Comment by hroncok** [comment] 2019-08-09 13:55
> Obsoleting python36 in the “Obsoletes:” sense would break every live python36 environment,

How?

**Comment by hroncok** [comment] 2019-08-09 14:14
I've just retired python36. When [this is pushed](https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2019-31bd12e515), I'll retire python-pip, python3-setuptools and python-wheel.

Every python36-foo package from EPEL works fine with RHEL python3 and there is no reason it should not.

**Comment by gordonmessmer** [comment] 2019-08-09 14:25
@nkadel  I certainly don't want to be rude, but if there were (hypothetically) a problem with the EPEL python3 work, this really wouldn't be the place to discuss it.  If you can describe or, better yet, demonstrate a problem, please do so on the devel mailing list.  Miro's time is limited and valuable, and I'd like to keep it focused on the remaining pull requests.  :)

**Comment by sergiomb2** [comment] 2020-05-18 21:30
Hi,

`yum install  "python3dist(pbr)"` doesn't work on epel 7, how we fix `BuildRequires:  python3dist(pbr)` that was produce by pyp2rpm ? 

Thank you

**Comment by nkadel** [comment] 2021-05-21 03:30
It's been almost two years.  There are 479 python36-* RPMs still present in EPEL, not mentioning the ones that have been obsoleted by RHEL published RPM's. pyp2rpm for fedora still produces "python3dist" requirements. While using the "-o epel7" option to use the RHEL 7 compatible format with "python3_pkgversion" based requirements, there are still packages that still have not completed the migration.

It's an unfortunate consequence of the decision to by Red Hat to use "python3-" instead of "python36-" for compatible package naming, especially since now other Red Hat based operating systems such as Amazon Linux 2 are using "python3-" for package names and dependencies, but for python 3.7.

The undefined macro for python3dist remains a big problem resolving these dependencies. Is there any graceful way to provide this, say having pyp2rpm provide a "if not defined, define this macro" statement?

**Comment by gordonmessmer** [comment] 2021-05-23 20:33
> It's been almost two years.

Yes, it has, and the issue originally reported was fixed in 3.3.4, so I will close this issue.

You previously suggested using the "python%{python3_pkgversion}-" form of dependencies in Fedora rather than "python3dist" macro, but I believe that is unsuitable as the guidelines refer to the latter:

https://docs.fedoraproject.org/en-US/packaging-guidelines/Python/

If you believe the guidelines should change, that should be discussed elsewhere.  Please open a new issue if pyp2rpm does not follow packaging guidelines in any case.

**Closed as completed by gordonmessmer** 2021-05-23 20:33 UTC
Labels: bug, epel

**Comment by nkadel** [comment] 2021-05-23 22:44
I don't know why you think it was fixed. It is absolutely not, I tested it several days ago. Please do not mark tickets as fixed or close tickets that have not been fixed, especially when the lack of a fix is so easily verified. It is possible to use "pyp2rpm -o epel7' to get a .spec file with the python3_pkgversion workaround, but it means maintaining distinct .spec files for fedora or RHEL 8, and for RHEL 7.

I agree that activating python3_pkgversion is awkward and unnecessary, but using it is *exactly* the workaround published for use with the 'pyp2rpm -o epel7' option. Unfortunately, it means that developers have to maintain two sets of .spec files, onf for Fedora or RHEL 8, and a distinct set for RHEL 7 based operating systems. It's ugly.

The rpm file with the relevant python3dist macros is /usr/lib/rpm/macros.python on RHEL 7. It is /usr/lib/rpm/macros.d/macro.s.python-srpm on RHEL 8 and Fedora. Would it be reasonable, or supportable, to declare these macros if missing for RHEL 7 based pyp2rpm? It's a bit ugly, but it could resolve some real compatibility issues with Fedora publishec packages, backporting them to EPE as needed.

**Comment by gordonmessmer** [comment] 2021-05-23 23:22
> I don't know why you think it was fixed

The issue originally reported was simply that "pyp2rpm -o epel7" would use the epel7 rules, but the fedora template, resulting in a spec that wasn't usable on epel7.  That issue is fixed.

> Would it be reasonable, or supportable, to declare these macros if missing for RHEL 7 based pyp2rpm? It's a bit ugly, but it could resolve some real compatibility issues with Fedora publishec packages, backporting them to EPE as needed.

I don't think it would.  Unless I'm mistaken, there are over 500 python3 modules packaged in RHEL7 and EPEL, but only about 200 of them include the "python3.6dist()" form of provides.  The problem isn't simply that pyp2rpm's output isn't using desirable macros, it's that most of the packages available don't have that form available to select, which isn't something that can be fixed in pyp2rpm.

**Comment by nkadel** [comment] 2021-05-24 01:20
The workaround is incomplete. While the selection of epel7 is working better, the incompatibility of the fedora default format with RHEL 7 based systems remains. And it's still widespread throughout  the EPEL infrastructure, where many if not most of them have to be built with different .spec files for RHEL 7.

Providing tools in pyp2rpm to activate those python3dist and similar macros might help provide compatibility for Fedora published packages to be trivially backported to RHEL 7, rather than the current laborious "Provide a new .spec file, use the python3_pkgversoin macros, and have it be unacceptable  for publication to Fedora". An ideal fix would be get Red Hat to enable the python3dist syntax in their /etc/rpm/ published macros, but I'm not sure I could talk them into that right now.

**Comment by sergiomb2** [comment] 2021-05-24 08:56
is related with https://bugzilla.redhat.com/show_bug.cgi?id=1812665#c11 ?
